<?php

namespace BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Get the comments for a certain blog
     * 
     * @param int $blogId
     * @param boolean $approved
     * @return Comment[]
     */
    public function getCommentsForBlog($blogId, $approved = true) {
        $comments = $this->createQueryBuilder('c')
                        ->select('c')
                        ->where('c.blog = :id')
                        ->setParameter('id', $blogId)
                        ->andWhere('c.approved = :approved')
                        ->setParameter('approved', $approved)
                        ->orderBy('c.createdAt', 'ASC')
                        ->getQuery()->getResult();
        
        return $comments;
    }

}
